INSERT INTO PLANO( NOME)  VALUES ('NorteEuropa');
INSERT INTO PLANO( NOME)  VALUES ('PampulhaIntermedica');
INSERT INTO PLANO( NOME)  VALUES ('DentalSorriso');
INSERT INTO PLANO( NOME)  VALUES ('MenteSaCorpoSao');


INSERT INTO EMPRESA(NOME)  VALUES ('Acme Co');
INSERT INTO EMPRESA(NOME)  VALUES ('Tio Patinhas Bank');

INSERT INTO COLABORADOR (NOME, CPF, DT_ADMISSAO, EMAIL, ENDERECO, PESO, ALTURA, HORAS_MEDITADAS)  
		 VALUES ('Mariscreide', '333.444.555-88',CURRENT_TIMESTAMP(),'Mariscreide@gmail.com','Rua dois, 2888 - Guarulhos - SP', 65, 2, 10);

INSERT INTO PLANOS_DA_EMPRESA(EMPRESA_ID, PLANO_ID) VALUES (1,1);
INSERT INTO PLANOS_DA_EMPRESA(EMPRESA_ID, PLANO_ID) VALUES (1,3);
INSERT INTO PLANOS_DA_EMPRESA(EMPRESA_ID, PLANO_ID) VALUES (2,2);
INSERT INTO PLANOS_DA_EMPRESA(EMPRESA_ID, PLANO_ID) VALUES (2,3);
INSERT INTO PLANOS_DA_EMPRESA(EMPRESA_ID, PLANO_ID) VALUES (2,4);

